[project]
name = "scratchpad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apexpy>=2.1.0",
    "astropy>=7.0.1",
    "cartopy>=0.25.0",
    "cdflib>=1.3.3",
    "chaosmagpy>=0.13.1",
    "geospacelab>=0.11.4",
    "h5py>=3.13.0",
    "hapiclient",
    "hdf5storage>=0.2.2",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "markdown>=3.7",
    "matplotlib>=3.10.1",
    "openpyxl>=3.1.5",
    "pip>=25.2",
    "pooch>=1.8.2",
    "ppigrf>=2.1.0",
    "pyamps>=1.7.0",
    "pycdfpp>=0.7.6",
    "pygmt>=0.17.0",
    "pyproj>=3.7.1",
    "pyshtools>=4.13.1",
    "spacepy>=0.7.0",
    "statsmodels>=0.14.4",
    "sunpy>=6.1.1",
    "swarmpal>=0.1.0",
    "swarmpal-mma",
    "tabulate>=0.9.0",
    "viresclient>=0.12.3",
    "watermark>=2.5.1",
]

[tool.uv.sources]
swarmpal = { path = "../SwarmPAL", editable = true }
swarmpal-mma = { workspace = true }
viresclient = { path = "../VirES-Python-Client", editable = true }
hapiclient = { git = "https://github.com/hapi-server/client-python" }

[tool.uv.workspace]
members = ["BGS-MMA-2E/upstream_MMA_2E", "test-chaos-amps"]
